name: SparkUCX CI

on:
  pull_request:
    branches:
    - master

jobs:     
  build-sparkucx:
    needs: install-jucx
    strategy:
      matrix:
        spark_version: [2.2.0, 2.3.0, 2.4.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package -Pspark-${{ matrix.spark_version }} --file pom.xml
